spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/file_sharing_app
      username: postgres
      password: 123456


  driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update